name: draga
description: A collaborative multi-canvas drawing board

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_colorpicker: ^1.0.3
  flutter_hooks: ^0.18.5+1
  flutter_svg: ^1.1.1+1
  file_saver: ^0.1.1
  font_awesome_flutter: ^10.2.1
  url_launcher: ^6.1.6
  universal_html: ^2.0.8
  image_picker: ^0.8.6
  file_picker: ^5.2.2
  image: ^3.2.2
  flutter_dialog_manager: ^1.0.0+4
  lottie: ^2.0.0
  steganograph:
    git:
      url: git@github.com:Crazelu/steganograph.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/animations/

